// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import (
	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// Server is an autogenerated mock type for the Server type
type Server struct {
	mock.Mock
}

// Register provides a mock function with given fields: gRPCServer
func (_m *Server) Register(gRPCServer *grpc.Server) {
	_m.Called(gRPCServer)
}

// NewServer creates a new instance of Server. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Server {
	mock := &Server{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
