// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import (
	net "net"
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// APIClient is an autogenerated mock type for the APIClient type
type APIClient struct {
	mock.Mock
}

// DoRequest provides a mock function with given fields: request
func (_m *APIClient) DoRequest(request *http.Request) (*http.Response, error) {
	ret := _m.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for DoRequest")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(*http.Request) (*http.Response, error)); ok {
		return rf(request)
	}
	if rf, ok := ret.Get(0).(func(*http.Request) *http.Response); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLocalIP provides a mock function with given fields:
func (_m *APIClient) GetLocalIP() (net.IP, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLocalIP")
	}

	var r0 net.IP
	var r1 error
	if rf, ok := ret.Get(0).(func() (net.IP, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() net.IP); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.IP)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendMetricsData provides a mock function with given fields: data
func (_m *APIClient) SendMetricsData(data *[]byte) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for SendMetricsData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*[]byte) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAPIClient creates a new instance of APIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAPIClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *APIClient {
	mock := &APIClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
