// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/e1m0re/grdn/internal/models"
)

// MetricsService is an autogenerated mock type for the MetricsService type
type MetricsService struct {
	mock.Mock
}

// GetMetric provides a mock function with given fields: ctx, mType, mName
func (_m *MetricsService) GetMetric(ctx context.Context, mType string, mName string) (*models.Metric, error) {
	ret := _m.Called(ctx, mType, mName)

	if len(ret) == 0 {
		panic("no return value specified for GetMetric")
	}

	var r0 *models.Metric
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.Metric, error)); ok {
		return rf(ctx, mType, mName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.Metric); ok {
		r0 = rf(ctx, mType, mName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Metric)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, mType, mName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMetricsList provides a mock function with given fields: ctx
func (_m *MetricsService) GetMetricsList(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMetricsList")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PingDB provides a mock function with given fields: ctx
func (_m *MetricsService) PingDB(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PingDB")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateMetric provides a mock function with given fields: ctx, metric
func (_m *MetricsService) UpdateMetric(ctx context.Context, metric models.Metric) error {
	ret := _m.Called(ctx, metric)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMetric")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Metric) error); ok {
		r0 = rf(ctx, metric)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateMetrics provides a mock function with given fields: ctx, metrics
func (_m *MetricsService) UpdateMetrics(ctx context.Context, metrics models.MetricsList) error {
	ret := _m.Called(ctx, metrics)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMetrics")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.MetricsList) error); ok {
		r0 = rf(ctx, metrics)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMetricsService creates a new instance of MetricsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricsService {
	mock := &MetricsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
